scuba_app/models/__init__.py
from .base import db, migrate, ma, bcrypt, login_manager


def init_app(app):
    db.init_app(app)
    ma.init_app(app)
    migrate.init_app(app, db, ma)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    

scuba_app/models/base.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_marshmallow import Marshmallow
from flask_bcrypt import Bcrypt
from flask_login import LoginManager, login_user, current_user, logout_user, login_required




db = SQLAlchemy()
ma= Marshmallow()
migrate = Migrate()
bcrypt = Bcrypt()
login_manager= LoginManager()

scuba_app/models/country.py
from .base import db, login_manager, ma
#from ..routes .user .forms import UserMixin
#from .user import User
#from marshmallow_sqlalchemy import ModelSchema


class Sites(db.Model):
    __tablename__ = 'sites'
    id = db.Column(db.Integer, primary_key=True)
    site_name=db.Column(db.String, unique=True)
    countries_name = db.Column(db.String, nullable=False)
    countries_dive_avg_depth = db.Column(db.String, nullable=False)
    latitude=db.Column(db.String, nullable=False)
    longitude=db.Column(db.String, nullable=False)
    diver_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)

    def __init__(self ,countries_name, countries_dive_name, countries_dive_avg_depth, latitude,longitude):
        self.site_name=countries_dive_name
        self.countries_name=countries_name
        self.countries_dive_avg_depth=countries_dive_avg_depth
        self.latitude=latitude
        self.longitude=longitude

    def __repr__(self):
        return '<Sites %r>'%self.site_name

    

    

'''
class CountrySchema(ma.Schema):
    class Meta:
        fields = (
            'id',
            'countries_dive_name',
            'countries_name',
            'countries_dive_avg_depth',
            'latitude',
            'longitude'
        )
'''



class SitesSchema(ma.Schema):
    class Meta:
        fields = (
            'id',
            'site_name',
            'countries_dive_avg_depth',
            'latitude',
            'longitude',
            'countries_name'
        )


sites_schema=SitesSchema(many=True)
site_schema=SitesSchema()

scuba_app/models/user.py
from .base import db, login_manager, ma

from flask_login import UserMixin
from .country import sites_schema, Sites, site_schema

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    #posts= db.relationship('Sites', secondary=saves, backref=db.backref('saved', lazy= 'dynamic'))
    diving_sites = db.relationship('Sites', backref='diver', lazy=True)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"

scuba_app/routes/user/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, SubmitField, SelectField, PasswordField, BooleanField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email, InputRequired, ValidationError
from werkzeug.security import generate_password_hash, check_password_hash 
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from ...models.user import User



class RegisterForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class CountryForm(Form):
    choices = [('Country', 'Country')]
    select = SelectField('Search for country:', choices=choices)
    search = StringField('')

scuba_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from redis import Redis
import rq



def create_app(config_class):
    from . import models, routes

    app = Flask(__name__)
    app.config.from_object(config_class)
    #app.redis = Redis(app.config['REDIS_HOST'], app.config['REDIS_PORT'])
    #app.task_queue = rq.Queue(connection=app.redis)

    models.init_app(app)
    
    routes.init_app(app)
    
   

    # need app_context functionality here
    return app

scuba_app/routes/__init__.py
from .user import userRoute
#from .init_ext import mail

def init_app(app):
    #mail.init_app(app)
    app.register_blueprint(userRoute)

scuba_app/routes/user/__init__.py
import os
import re
import arrow
import requests
import datetime
import json
import time
import geojson
from datetime import datetime
from flask import session, Blueprint, request, render_template, redirect, flash, url_for, current_app, jsonify, render_template_string
from redis import Redis
from rq.job import Job
from .forms import CountryForm
from .helperfunc import conversion, tasker
from pathlib import Path
# from .helper_func import send_confirmation_email, confirm_token
from .forms import RegisterForm, LoginForm
from flask_login import login_user, current_user, logout_user, login_required,AnonymousUserMixin
from ...models.base import db, bcrypt, login_manager
from ...models.user import User
from ...models.country import (sites_schema, Sites, site_schema)
from ...secrets import MAPBOX, OPENWEATHER_ID, TIDE_AUTH_ID

# this fetches the job id required for catching with Redis to call multipl API
def background_task(n):
    delay=2
    print("Task running")
    print(f"Simulating {delay} second delay")

    time.sleep(delay)
    print(len(n))
    print("Task Complete")

    return len(n)
    
 


# this class shows Guest when no user is logged in
class Anonymous(AnonymousUserMixin):
  def __init__(self):
    self.username = 'Guest'




userRoute = Blueprint('userRoute', __name__)




# this functions fetches the id and returns it as a simple string for other routes to use
@userRoute.route("/task")
def task():
    job = tasker()
    print('Job id: %s' % job.id)
    print('reached here')
    return 'Job id: {}'.format(job.id)


# this function gets the job id, writes to a JSON file and appends new data to the JSON file for the map
@userRoute.route("/geojson/<jobid>")
def geojson_submit(jobid):
    redis_conn = Redis()
    
    job = Job.fetch(jobid, connection=redis_conn)
    allapi=job.result
    print(len(allapi))
    # Opening JSON file 

    # f = open('/Users/assswain/Desktop/projects/Scuba-man/scuba_app/routes/user/sitee.json',) 
    f = open('/Users/deevyaswain/Desktop/projects/Scuba/Scuba-man/scuba_app/routes/user/sitee.json',) 
    
    # returns JSON object as a dictionary 
    data = json.load(f) 
    
    # Iterating through the json 
    # list 
   
    
    # Closing file 
    f.close()
    site=json.dumps(data)
    

    for i, data_point in enumerate(allapi):
        d1=data['features'][i]['properties']
        d2=allapi[i]
        d1['city']=d2['city']
        d1['description']=d2['description']
        d1['temperature']=d2['temperature']
        d1['wind_speed']=d2['wind_speed']
    
    # with open('/Users/assswain/Desktop/projects/Scuba-man/scuba_app/routes/user/sitee_update.json', 'w', encoding='utf-8') as f:
    with open('/Users/deevyaswain/Desktop/projects/Scuba/Scuba-man/scuba_app/routes/user/sitee_update.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
   

    print(type(data))

       

    return redirect(url_for('userRoute.maps'))
    






@userRoute.route('/login', methods=['GET', 'POST'])
def login():
    form=LoginForm()
    user = User.query.filter_by(email=form.email.data).first()
    # if the hashed password matches the one typed in by the user
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('userRoute.maps'))
    else:
        flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@userRoute.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password= bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('userRoute.login'))
    return render_template('signup.html', title='Register', form=form)


@userRoute.route("/logout")
def logout():
    login_manager.anonymous_user = Anonymous
    logout_user()
    return redirect(url_for('userRoute.maps'))



# helps in converting the GPS coordinate to normal lat long for the map to understand
@userRoute.route('/coordinate', methods=['GET', 'POST'])
def coordinata():
    array=[]
    listo=[]


    if request.method=="POST":
        form=request.form
        search_value=form['countries_name']
        print(search_value)
        search="%{}%".format(search_value)
        
        coordinate=Sites.query.filter(Sites.countries_name.like(search)).all()
       
        for e in coordinate:
            lat, lon = u'''{0}, {1}'''.format(e.latitude, e.longitude).split(',')
            u=[conversion(lon),conversion(lat)]
            e.latitude=conversion(lat)
            e.longitude=conversion(lon)
            array.append(u)
            listo.append(e.site_name)

 
        coordinate_output= sites_schema.dump(coordinate)

        session['my_var'] = array
        session['coord_var']= coordinate_output
        print(array)
   
    return redirect(url_for('userRoute.maps'))
    





@userRoute.route('/', methods=['GET'])
def simple():
    return redirect(url_for('userRoute.login'))





# this function handles all the api calls
@userRoute.route('/meh/<country>', methods=['GET'])
def index(country):
    cities=Sites.query.filter_by(site_name="{}".format(country)).first()
#    url from an api
    url = 'http://api.openweathermap.org/data/2.5/weather?lat={}&lon={}&units=metric&appid={}'
    

    weather_data = []
    lat=conversion(cities.latitude)
    lon=conversion(cities.longitude)
    print(lat, lon, 'string : latlong')
    
    # gathering the data from the api by sending in the latitude and logitude from the previous function 
    r1 =requests.get(url.format(lat,lon, OPENWEATHER_ID)).json()
    

    weather = { 
        'city' : cities.site_name,
        'temperature' : r1['main']['temp'],
        'description' : r1['weather'][0]['description'],
        'wind_speed': r1['wind']['speed'],
    }
 
    start = arrow.now().floor('day')
    end = arrow.now().shift(days=1).floor('day')
# this is used for authorizing with stormglass to use the API
    response1 = requests.get(
    'https://api.stormglass.io/v2/tide/extremes/point',
    params={
        'lat': lat,
        'lng': lon,
        'start': start.to('UTC').timestamp,  # Convert to UTC timestamp
        'end': end.to('UTC').timestamp,  # Convert to UTC timestam
    },
    headers={
        'Authorization': TIDE_AUTH_ID
    }
    )
    tide_data = response1.json()
    tidal_arr=[]
    for i in range(2):
        tidal={
            'height': "{:.2f}".format(tide_data['data'][i]['height']),
            'time': tide_data['data'][i]['time'],
            'type': tide_data['data'][i]['type'],
        }
        tidal_arr.append(tidal)
    #print(tide_data)
    
    response2 = requests.get(
        'https://api.stormglass.io/v2/weather/point',
        params={
            'lat': lat,
            'lng': lon,
            'params': ['waterTemperature'],
             # Convert to UTC timestamp
        },
        headers={
            'Authorization': TIDE_AUTH_ID
        }
        )
    wave_data=response2.json()
    
    waves={'water_temperature': wave_data['hours'][0]['waterTemperature']['noaa']}
    
    weather_data.append(weather)
    diving_site=weather['city']
    print(tidal_arr)
   
    # all of these sessions are passed around to different functions for a wuick method of sending data
    
    session['my_api_site']=diving_site
    session['my_api']=weather
    session['my_coord']=[lon, lat]
    session['my_site_name']=(cities.site_name, cities.countries_dive_avg_depth)
    session['tide']=tidal_arr
    session['waves']=waves
   
    return redirect(url_for('userRoute.maps'))



# this functions helps in storing user information by linking the sites database to the user database so that the user can store multipls locations
@userRoute.route('/save', methods=['GET'])
@login_required
def saveSite():
    site_name=session.get('my_api_site',[{1:1},{2:2}])
    site_obj=Sites.query.filter_by(site_name="{}".format(site_name)).first()
    print(site_obj.site_name)
    user_obj = User.query.filter_by(username=current_user.username).first_or_404()
    print('appending to user_obj')
    user_obj.diving_sites.append(site_obj)
    db.session.commit()
    print('saved diving site successfully')

    print(user_obj.diving_sites)
    return redirect(url_for('userRoute.maps'))


# this shows the stores location from the current usre as a json file
@userRoute.route('/display_location')
@login_required
def display_sites():
    user_obj = User.query.filter_by(username=current_user.username).first_or_404()
    site_names=[]
    for site in user_obj.diving_sites:
        print(site.site_name)
        site_names.append(site.site_name)
    return json.dumps(site_names)





# this is the main route that calles to the html page that displays the map and coordinates
@userRoute.route('/map',methods=['GET','POST'])

def maps():
 
    
    output = session.get('coord_var', [{1:1},{2:2}])
    my_var = session.get('my_var', None)
    my_weather=session.get('my_api',[{1:1},{2:2}])
    my_coord=session.get('my_coord', None)
    sito=session.get('my_site_name',None)
    tide=session.get('tide',[{1:1},{2:2}])
    waves=session.get('waves',[{1:1},{2:2}])
    
    # Opening JSON file 
    f = open('/Users/deevyaswain/Desktop/projects/Scuba/Scuba-man/scuba_app/routes/user/sitee_update.json',) 
 
    data = json.load(f) 

    f.close()

    searcher1=(output)
    form = RegisterForm()
    



    if form.validate_on_submit():
        
        hashed_password = generate_password_hash(form.password.data, method='sha256')

scuba_app/templates/api.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>What's the weather like?</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?, {{ name }}
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% for weather in weather_data %}
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ weather.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ weather.temperature }}° C</span>
                                        <br> {{ weather.description }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>

</html>

scuba_app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Scuba-man - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <!-- <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('userRoute.maps') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('userRoute.maps') }}">About</a>
            </div> -->
            <!-- Navbar Right Side -->
            <!-- <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('userRoute.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('userRoute.logout') }}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('userRoute.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('userRoute.signup') }}">Register</a>
              {% endif %}
            </div> -->
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <!-- <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div> -->
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

scuba_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('userRoute.signup') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

scuba_app/templates/signup.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('userRoute.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}